base_url = "https://cubero.org"
title = "Valeria Cubero"
build_search_index = true
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "auto"
favicon = "/icon/favicon.ico"
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url= "/posts", weight= 1 },
    { name= "/projects", url= "/projects", weight= 2 },
    { name= "/about", url= "/about", weight= 3 },
]

socials = [
    { name= "twitter", url= "https://twitter.com/0xVALUE", icon= "twitter" },
    { name= "mastodon", url= "https://mastodon.social/@0xval", icon = "mastodon" },
    { name= "github", url= "https://github.com/Valeria/", icon = "github" },
    { name= "email", url= "mailto:valeria@cubero.org", icon = "email" },
    
]

[extra.analytics]
enabled = true
goatcounter_user = "vcubero"
