base_url = "https://cubero.org"
title = "Valeria Cubero"
build_search_index = true
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "auto"

menu = [
    { name = "/posts", url= "/posts", weight= 1 },
    { name= "/projects", url= "/projects", weight= 2 },
    { name= "/about", url= "/about", weight= 3 },
]

socials = [
    { name= "twitter", url= "https://twitter.com/0xVALUE", icon= "twitter" },
    { name= "github", url= "https://github.com/Valeria/", icon = "github" },
]

[extra.analytics]
enabled = false
goatcounter_user = "not-matthias"
